language: node_js

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"

notifications:
  email: false

sudo: false

addons:
    code_climate:
        repo_token: 2c5810462b0704a2e860c6393cc04b25afd873705550e600584041ac570335ed

after_script:
  - codeclimate-test-reporter < lcov.info
